config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root to: 'book#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,
    presence: true

  validates :body,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
  	@books = Book.all
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render action: :index
    end
  end

  # 'render'はアクションを経由しないでビューに飛ぶ。その時、ビューが持つ変数が定義されていなければ再定義する必要がある。

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title,:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>

  <% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

	<div class="field">
	<h4>Title</h4>
	<%= f.text_field :title %>
	</div>

	<div class="field">
	<h4>Body</h4>
	<%= f.text_area :body %>
	</div>

	<div class="actions">
	<%= f.submit 'Update Book' %>
	</div>
<% end %>

<%= link_to "Show", book_path(@book) %>
<span>|</span>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<body>
<h1>Books</h1>
<table>
  <thead>
  	<tr>
  	  <th>Title</th>
  	  <th>Body</th>
      <th colspan="3"></th>
  	</tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
  	<tr>
  	  <td><%= book.title %></td>
  	  <td><%= book.body %></td>
  	  <td><%= link_to 'Show', book_path(book.id) %></td>
  	  <td><%= link_to "Edit", edit_book_path(book.id) %></td>
	    <td><%= link_to "Destroy", book_path(book.id), method: :delete, data: {confirm: 'Are you sure?'} %></td>
  	</tr>
    <% end %>
  </tbody>
</table>

<h2>New book</h2>

<%= form_for(@book) do |f| %>

  <% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
	<h4>Title</h4>
	<%= f.text_field :title %>
  </div>

  <div class="field">
	<h4>Body</h4>
	<%= f.text_area :body %>
  </div>

  <div class="actions">
	<%= f.submit 'Create Book' %>
  </div>
<% end %>

<!-- <%= link_to 'new.html.erb' ,new_book_path %> -->

</body>

app/views/books/new.html.erb
<h1>
  ようこそ <strong>Bookers</strong> へ！
</h1>
<p>
  <strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や
</p>
<p>
  印象を共有し交換することができます
</p>
<p>
  <%= link_to 'start', books_path %></a>
</p>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<p>
  <strong>Title: </strong><%= @book.title %>
</p>
<p>
  <strong>Body: </strong><%= @book.body %>
</p>
<%= link_to "Edit", edit_book_path(@book) %>
<span>|</span>
<%= link_to "Back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>